CREATE TABLE user_parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  equipped_key VARCHAR(255),
  updated_at TIMESTAMP(6),
  CONSTRAINT uk_user_parts_user_id UNIQUE (user_id),
  CONSTRAINT fk_user_parts_user FOREIGN KEY (user_id) REFERENCES users (id)
);
